language: node_js
node_js:
 - "4"
 - "6"
 - "node"
script:
  - npm install mocha fs d3 --save-dev
  - ./node_modules/mocha/bin/mocha
cache:
  directories:
    - node_modules
sudo: false
branches:
  only:
    - master
